import { ClerkProvider } from '@clerk/nextjs'
import './globals.css'
import type { Metadata } from 'next'
import { Amiri } from 'next/font/google'

const inter = Amiri({
  subsets: ['arabic'],
  weight: '700'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="ar" dir='rtl'>
        <body className={inter.className}>{children}</body>
      </html>
    </ClerkProvider>
  )
}
